version: '3.9' 

services:
    
  web:
    container_name: gin_session_auth
    build: ./gin_session_auth
    tty: true
    volumes:
      - ./gin_session_auth:/go/src
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend

  db:
    container_name: postgres-db
    image: postgres:14.0-alpine
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  postgres_volume:

networks:
  frontend:
    name: custom-frontend
  backend:
    name: custom-backend
