version: '3.9' 

services:
    
  frontend:
    container_name: react-web-app
    image: node:17-alpine
    volumes:
      - ./login-app:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
    networks:
      - frontend

  backend:
    container_name: gin-gonic
    build: ./gin-gonic
    tty: true
    volumes:
      - ./gin-gonic:/go/src
    # command: sh -c "go run main.go"
    ports:
      - 3333:3333
    networks:
      - frontend
      - backend

  db:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  postgres_volume:

networks:
  frontend:
    name: custom-frontend
  backend:
    name: custom-backend
